const WebApp = {
  initData: '',
  initDataUnsafe: {
    user: null,
  },
  colorScheme: 'dark' as const,
  themeParams: {},
  isExpanded: false,
  viewportHeight: 0,
  viewportStableHeight: 0,
  platform: 'unknown',
  version: '6.0',
  ready: () => {},
  expand: () => {},
  close: () => {},
  enableClosingConfirmation: () => {},
  disableClosingConfirmation: () => {},
  sendData: () => {},
  openLink: () => {},
  openTelegramLink: () => {},
  openInvoice: () => {},
  showPopup: () => {},
  showAlert: () => {},
  showConfirm: () => {},
  setHeaderColor: () => {},
  setBackgroundColor: () => {},
  MainButton: {
    text: '',
    color: '',
    textColor: '',
    isVisible: false,
    isActive: true,
    isProgressVisible: false,
    show: () => {},
    hide: () => {},
    enable: () => {},
    disable: () => {},
    showProgress: () => {},
    hideProgress: () => {},
    setText: () => {},
    onClick: () => {},
    offClick: () => {},
    setParams: () => {},
  },
  BackButton: {
    isVisible: false,
    show: () => {},
    hide: () => {},
    onClick: () => {},
    offClick: () => {},
  },
  HapticFeedback: {
    impactOccurred: () => {},
    notificationOccurred: () => {},
    selectionChanged: () => {},
  },
  onEvent: () => {},
  offEvent: () => {},
};

export default WebApp;
